---
name: Librespot
version: '0.5'
slug: librespot
description: Spotify Connect piped to Snapcast
url: https://github.com/selleronom/hassio-addons/tree/master/librespot
startup: services
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
boot: auto
hassio_api: true
hassio_role: default
host_dbus: true
host_network: true
init: false
apparmor: false
map:
- share:rw
options:
  name: Hass.io
  bitrate: 320
  username: ''
  password: ''
  initial_volume: 50
  disable_audio_cache: true
  linear_volume: false
  enable_volume_normalisation: true
  disable_discovery: true
  disable_gapless: true
  log_level: info
schema:
  name: str
  bitrate: match(^(96|160|320)$)
  username: str
  password: str
  initial_volume: int
  disable_audio_cache: bool
  linear_volume: bool
  enable_volume_normalisation: bool
  disable_discovery: bool
  disable_gapless: bool
  log_level: match(^(trace|debug|info|notice|warning|error|fatal)$)?
