name: WireGuard Client
version: "1.0.0"
slug: wireguardclient
description: A WireGuard client for Home Assistant
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - ssl:rw
privileged:
  - NET_ADMIN
  - SYS_MODULE
host_network: true