name: Snapserver
version: '0.5'
slug: snapserver
description: Snapcast server
url: https://github.com/mecanisoft/hassio-addons-ex/tree/master/snapserver
startup: services
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
boot: auto
hassio_api: true
hassio_role: default
host_dbus: true
init: false
apparmor: false
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
  3689/tcp: 3689
  5000/tcp: 5000
  5000/tcp: 5000
  5001/tcp: 5001
  5002/tcp: 5002
  5003/tcp: 5003
  5004/tcp: 5004
  5005/tcp: 5005
  3689/tcp: 3689
  6000/udp: 6000
  6001/udp: 6001
  6002/udp: 6002
  6003/udp: 6003
  6004/udp: 6004
  6005/udp: 6005
  5353/tcp: 5353
  
ports_description:
  1704/tcp: Snapcast server port
  1705/tcp: Snapcast TCP control port (set empty to disable)
  1780/tcp: Snapcast HTTP control port (set empty to disable)
  3689/tcp: Airport
  5000/tcp: Airport
  5001/tcp: Aiport
  5002/tcp: Airport
  5003/tcp: Airport
  5004/tcp: Airport
  5005/tcp: Airport
  6001/udp: Airport
  6002/udp: Airport
  6003/udp: Airport
  6004/udp: Airport
  6005/udp: Airport
  5353/tcp: Avahi
  
map:
- share:rw
options:
  stream:
    streams:
      - pipe:///share/snapfifo/librespot?name=SpotifyConnect&sampleformat=44100:16:2
      - pipe:///share/snapfifo/mopidy?name=Mopidy&sampleformat=48000:16:2
      - pipe:///tmp/mpd-notify?name=Notify&sampleformat=44100:16:2
      - pipe:///share/snapfifo/shairport?name=Shairport&sampleformat=44100:16:2
      - pipe:///tmp/sharesound/snapfifo?name=Radio
    buffer: '1000'
    codec: flac
    send_to_muted: 'false'
    sampleformat: '48000:16:2'
  http:
    enabled: 'true'
    doc_root: "/usr/share/snapserver/snapweb"
  tcp:
    enabled: 'true'
  pulseaudio:
    pipe_path:'/pipes/phono'
  logging:
    enabled: 'false'
  server:
    threads: "-1"
    datadir: "/share/snapcast/"
schema:
  stream:
    streams:
    - str
    buffer: int
    codec: str
    send_to_muted: str
    sampleformat: str
  http:
    enabled: str
    doc_root: str
  tcp:
    enabled: str
  logging:
    enabled: str
  server:
    threads: int
    datadir: str
